site_name: SIB Training Cookbook
nav:
  - Home: index.md
  - Plan:
    - Identify and assess training needs: topics/training_needs.md 
    - Course Programme and Planning: procedures/course_programme.md
    - Call for New Courses: procedures/call_new_courses.md

  - Design:
    # merge the course design pages below
    - Course Design: topics/course_design.md
    - Design the Course: procedures/design_course.md
    - Types of courses: procedures/delivering_course/type_course.md
    - Course Description: procedures/course_coordination/course_description.md

  - Develop:
    - Course material life cycle: procedures/course_material.md
    # merge the metadata page with the FAIR page
    - Make course materials open and FAIR: topics/FAIR-training-flowchart/flowchart_description.md
    - Metadata mapping: topics/metadata.md
  - Deliver:
  # course coordination could become one page or less pages
    - Course coordination:
      - Register Participants: procedures/course_coordination/participants/register_participants.md
      - Open and announce the course: procedures/course_coordination/participants/open_course.md
      - Manage Payments: procedures/course_coordination/participants/manage_payments.md
      - Send practical information to registered participants: procedures/course_coordination/participants/send_info.md
      - Attendance list and exams: procedures/course_coordination/participants/attendance_exam.md
      - Thank participants: procedures/course_coordination/participants/thank_participants.md
      - Update courseadmin (after course): procedures/course_coordination/participants/after_course.md
      - Certificates: procedures/course_coordination/participants/certificate.md
      - Record Lectures: procedures/course_coordination/record_lectures.md
      - Course Administrative tasks: procedures/course_coordination/admin_tasks.md
      - Reimbursements: procedures/course_coordination/reimbursements.md
      - Course Locations: procedures/course_coordination/course_location.md
    - Delivering the Course: procedures/delivering_course/deliver_course.md
  - Evaluate:
    -  ECTS credits and Exam: topics/ECTS_exam.md
    # merge evaluation and feedback
    - Course Evaluation: topics/course_evaluation.md
    - Feedback: procedures/course_coordination/feedback.md
  # E-learning could be combined in one page   
  - E-learning:
    - Plan:
      - Identify and assess e-learning needs: topics/elearning/elearning_needs.md
      - E-learning plan: topics/elearning/elearning_plan.md
    - Design:
      - E-learning design: topics/elearning/elearning_design.md
    - Develop:
      - E-learning material: topics/elearning/elearning_material.md
      - Make e-learning materials open and FAIR: topics/elearning/elearning_openandFAIR.md
    - Deliver:
      - Course coordination: topics/elearning/elearning_coordination.md
    - Evaluate:
      - E-learning evaluation: topics/elearning/elearning_evaluation.md
  - Glossary: Glossary.md

watch:
  - includes

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: "#D40000"
      accent: "#999999"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: "#F6D0D0"
      accent: "#999999"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Repository
repo_name: sib-swiss/training-cookbook
repo_url: https://github.com/sib-swiss/training-cookbook
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/definitions.md

extra_css:
  - stylesheets/extra.css

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: sib-swiss/training-cookbook
      branch: 11-add-date-and-committers-to-each-page
      token: !ENV ["CI_JOB_TOKEN"]
  # - git-authors

