site_name: SIB Training Cookbook
nav:
    - Home: index.md
    - Topics: 
      - Identify and assess training needs: topic/training_needs.md      
      - Course Design: topic/course_design.md
      - ECTS credits and Exam: topic/ECTS_exam.md
      - Course Evaluation: topic/course_evaluation.md
      - Make course materials open and FAIR: topic/FAIR-training-flowchart/flowchart_description.md
      - Metadata mapping: topic/metadata.md
    - Procedures:
      - Course Programme and Planning: procedure/course_programme.md
      - Call for New Courses: procedure/call_new_courses.md
      - Design the Course: procedure/design_course.md
      - Course material life cycle: procedure/course_material.md
      - Deliver the Course:
        - Delivering the Course: procedure/delivering_course/deliver_course.md
        - Types of courses: procedure/delivering_course/type_course.md
      - Course Coordination:
        - Course Description: procedure/course_description.md
        - Participants:
          - Open and announce the course: procedure/participants/open_course.md
          - Register Participants: procedure/participants/register_participants.md
          - Manage Payments: procedure/participants/manage_payments.md
          - Send practical information to registered participants: procedure/participants/send_info.md
          - Attendance list and exams: procedure/participants/attendance_exam.md
          - Thank participants: procedure/participants/thank_participants.md
          - Update courseadmin (after course): procedure/participants/after_course.md
          - Certificates: procedure/participants/certificate.md
        - Feedback: procedure/feedback.md
        - Record Lectures: procedure/record_lectures.md
        - Course Administrative tasks: procedure/admin_tasks.md
        - Reimbursements: procedure/reimbursements.md
        - Course Locations: procedure/course_location.md
    - E-learning:
      - Identify and assess e-learning needs: E-learning/elearning_needs.md
      - E-learning plan: E-learning/elearning_plan.md
      - E-learning design: E-learning/elearning_design.md
      - E-learning material: E-learning/elearning_material.md
      - E-learning evaluation: E-learning/elearning_evaluation.md
      - Make e-learning materials open and FAIR: E-learning/elearning_openandFAIR.md
      - Course coordination: E-learning/elearning_coordination.md
    - Glossary: Glossary.md

watch:
  - includes

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: "#D40000"
      accent: "#999999"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: "#F6D0D0"
      accent: "#999999"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Repository
repo_name: sib-swiss/training-cookbook
repo_url: https://github.com/sib-swiss/training-cookbook
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/definitions.md

extra_css:
  - stylesheets/extra.css