site_name: SIB Training Cookbook
nav:
    - Home: index.md
    - Topics: 
      - Identify and assess training needs: topics/training_needs.md      
      - Course Design: topics/course_design.md
      - ECTS credits and Exam: topics/ECTS_exam.md
      - Course Evaluation: topics/course_evaluation.md
      - Make course materials open and FAIR: topics/FAIR-training-flowchart/flowchart_description.md
      - Metadata mapping: topics/metadata.md
      - E-learning:
        - Identify and assess e-learning needs: topics/elearning/elearning_needs.md
        - E-learning plan: topics/elearning/elearning_plan.md
        - E-learning design: topics/elearning/elearning_design.md
        - E-learning material: topics/elearning/elearning_material.md
        - E-learning evaluation: topics/elearning/elearning_evaluation.md
        - Make e-learning materials open and FAIR: topics/elearning/elearning_openandFAIR.md
        - Course coordination: topics/elearning/elearning_coordination.md
    - Procedures:
      - Course Programme and Planning: procedures/course_programme.md
      - Call for New Courses: procedures/call_new_courses.md
      - Design the Course: procedures/design_course.md
      - Course material life cycle: procedures/course_material.md
      - Deliver the Course:
        - Delivering the Course: procedures/delivering_course/deliver_course.md
        - Types of courses: procedures/delivering_course/type_course.md
      - Course Coordination:
        - Course Description: procedures/course_coordination/course_description.md
        - Participants:
          - Open and announce the course: procedures/course_coordination/participants/open_course.md
          - Register Participants: procedures/course_coordination/participants/register_participants.md
          - Manage Payments: procedures/course_coordination/participants/manage_payments.md
          - Send practical information to registered participants: procedures/course_coordination/participants/send_info.md
          - Attendance list and exams: procedures/course_coordination/participants/attendance_exam.md
          - Thank participants: procedures/course_coordination/participants/thank_participants.md
          - Update courseadmin (after course): procedures/course_coordination/participants/after_course.md
          - Certificates: procedures/course_coordination/participants/certificate.md
        - Feedback: procedures/course_coordination/feedback.md
        - Record Lectures: procedures/course_coordination/record_lectures.md
        - Course Administrative tasks: procedures/course_coordination/admin_tasks.md
        - Reimbursements: procedures/course_coordination/reimbursements.md
        - Course Locations: procedures/course_coordination/course_location.md

    - Glossary: Glossary.md

watch:
  - includes

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: "#D40000"
      accent: "#999999"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: "#F6D0D0"
      accent: "#999999"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Repository
repo_name: sib-swiss/training-cookbook
repo_url: https://github.com/sib-swiss/training-cookbook
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/definitions.md

extra_css:
  - stylesheets/extra.css